Git hook scripts update

diff --git a/code/helper/pre-commit.install b/code/helper/pre-commit.install
--- a/code/helper/pre-commit.install
+++ b/code/helper/pre-commit.install
@@ -1,1 +1,39 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+# Based on code from : https://dev.to/bdelespierre/how-to-setup-git-commit-hooks-for-php-42d1
+# Based on code from : https://gist.github.com/Pilipo/e52ff5ac38fba9e1f5ed966816de41e9
+
+# get bash colors and styles here:
+# http://misc.flogisoft.com/bash/tip_colors_and_formatting
+C_RESET='\e[0m'
+C_RED='\e[31m'
+C_GREEN='\e[32m'
+C_YELLOW='\e[33m'
+
+function __run() #(step, name, cmd)
+{
+    local color output exitcode
+
+    printf "${C_YELLOW}[%s]${C_RESET} %-20s" "$1" "$2"
+    output=$(eval "$3" 2>&1)
+    exitcode=$?
+
+    if [[ 0 == $exitcode || 130 == $exitcode ]]; then
+        echo -e " - Status : ${C_GREEN} OK !${C_RESET}"
+    else
+        if [ $1 == "1/2" ]; then
+            echo -e " - Status : ${C_YELLOW} SAVE MODIFICATION !${C_RESET}\n\n$output"
+        else
+            echo -e " - Status : ${C_RED} ERROR DETECTED !${C_RESET}\n\n$output"
+        fi
+        exit 1
+    fi
+}
+
+modified="git diff --name-only --cached  | grep -i \"\.php$\""
+ignore="code/vendor"
+phpcbf="code/vendor/bin/phpcbf --report=code --colors --report-width=80 --ignore=${ignore} -p"
+phpcs="code/vendor/bin/phpcs --report=code --colors --report-width=80 --ignore=${ignore} -p"
+
+__run "1/2" "Code Sniffer : Correcting coding standard violations" "${modified} | xargs -r ${phpcbf}"
+__run "2/2" "Code Sniffer : Detecting uncorrected coding standard violations" "${modified} | xargs -r ${phpcs}"
